blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (BlogArticleCreateView, BlogArticleListView, BlogArticleDetailView, BlogArticleUpdateView,
                        BlogArticleDeleteView)

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogArticleCreateView.as_view(), name='create'),
    path('', BlogArticleListView.as_view(), name='list'),
    path('delete/<int:pk>/', BlogArticleDeleteView.as_view(), name='delete'),
    path('edit/<int:pk>/', BlogArticleUpdateView.as_view(), name='edit'),
    path('view/<int:pk>/', cache_page(60)(BlogArticleDetailView.as_view()), name='view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import (HomeView, ClientListView, ClientCreateView, ClientDeleteView, ClientUpdateView,
                           ClientDetailView, MessageListView, MessageCreateView, MessageUpdateView, MessageDeleteView,
                           MessageDetailView, MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView,
                           MailingDetailView, LogListView)

app_name = MailingConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('create/', ClientCreateView.as_view(), name='create'),
    path('clients_list/', ClientListView.as_view(), name='clients_list'),
    path('delete/<int:pk>/', ClientDeleteView.as_view(), name='delete'),
    path('edit/<int:pk>/', ClientUpdateView.as_view(), name='edit'),
    path('view/<int:pk>/', cache_page(60)(ClientDetailView.as_view()), name='view'),
    path('messages_list/', MessageListView.as_view(), name='messages_list'),
    path('message_create/', MessageCreateView.as_view(), name='create_message'),
    path('message_view/<int:pk>/', cache_page(60)(MessageDetailView.as_view()), name='view_message'),
    path('message_edit/<int:pk>/', MessageUpdateView.as_view(), name='edit_message'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),
    path('mailings_list/', MailingListView.as_view(), name='mailings_list'),
    path('mailing_create/', MailingCreateView.as_view(), name='create_mailing'),
    path('mailing_view/<int:pk>/', MailingDetailView.as_view(), name='view_mailing'),
    path('mailing_edit/<int:pk>/', MailingUpdateView.as_view(), name='edit_mailing'),
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='delete_mailing'),
    path('logs_list/', LogListView.as_view(), name='logs_list'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, reset_password, ProfileView, UserListView, toggle_activity

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('reset_password/', reset_password, name='reset_password'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('toggle_activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

mailing/models.py
from django.db import models

from users.models import User

NULLABLE = {"null": True, "blank": True}


class Client(models.Model):
    """
    Модель для хранения информации о клиенте
    """

    name = models.CharField(max_length=100, verbose_name='Имя')
    email = models.EmailField(max_length=100, verbose_name='Электронная почта')
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    owner = models.ForeignKey(User, verbose_name='Владелец', on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"
        ordering = ("name",)


class Message(models.Model):
    """
    Модель для хранения информации о сообщении для рассылки
    """

    title = models.CharField(max_length=255, verbose_name="Тема")
    message = models.TextField(verbose_name="Сообщение")
    owner = models.ForeignKey(User, verbose_name='Владелец', on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"


class Mailing(models.Model):
    """
    Модель для хранения информации о рассылке
    """

    DAILY = "Раз в день"
    WEEKLY = "Раз в неделю"
    MONTHLY = "Раз в месяц"

    PERIODICITY_CHOICES = [
        (DAILY, "Раз в день"),
        (WEEKLY, "Раз в неделю"),
        (MONTHLY, "Раз в месяц"),
    ]

    CREATED = "Создана"
    STARTED = "Запущена"
    COMPLETED = "Завершена"

    STATUS_CHOICES = [
        (COMPLETED, "Завершена"),
        (CREATED, "Создана"),
        (STARTED, "Запущена"),
    ]

    name = models.CharField(max_length=150, verbose_name="Название")
    description = models.TextField(**NULLABLE, verbose_name="Описание", help_text="не обязательное поле")
    status = models.CharField(max_length=150, choices=STATUS_CHOICES, default=CREATED, verbose_name="Статус")
    periodicity = models.CharField(
        max_length=150,
        choices=PERIODICITY_CHOICES,
        default=DAILY,
        verbose_name="Периодичность",
    )
    start_date = models.DateTimeField(
        verbose_name="Дата начала",
        **NULLABLE,
        help_text="(формат 11.05.2024) не обязательное поле",
    )
    end_date = models.DateTimeField(verbose_name='Дата окончания', **NULLABLE, help_text='не обязательное поле')
    next_send_time = models.DateTimeField(verbose_name='Время следующей отправки', **NULLABLE)
    clients = models.ManyToManyField(Client, related_name='mailing', verbose_name='Клиенты для рассылки')
    message = models.ForeignKey(Message, verbose_name='Cообщение', on_delete=models.CASCADE, **NULLABLE)
    owner = models.ForeignKey(User, verbose_name='Владелец',  on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f"{self.name}, статус: {self.status}"

    def save(self, *args, **kwargs):
        if not self.next_send_time:
            self.next_send_time = self.start_date
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = ("name",)
        permissions = [
            ('deactivate_mailing', 'Can deactivate mailing'),
            ('view_all_mailings', 'Can view all mailings'),
        ]


class Log(models.Model):
    """
    Модель для хранения информации о попытках рассылок
    """
    SUCCESS = 'Успешно'
    FAIL = 'Неуспешно'
    STATUS_VARIANTS = [
        (SUCCESS, 'Успешно'),
        (FAIL, 'Неуспешно'),
    ]

    time = models.DateTimeField(
        verbose_name="Дата и время попытки отправки", auto_now_add=True
    )
    status = models.CharField(max_length=50, choices=STATUS_VARIANTS, verbose_name='Cтатус рассылки')
    server_response = models.CharField(
        max_length=150, verbose_name="Ответ сервера почтового сервиса", **NULLABLE
    )
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name="Рассылка")

    def __str__(self):
        return f"{self.mailing} {self.time} {self.status} {self.server_response}"

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылки"

mailing/forms.py
from django import forms
from .models import Client, Mailing, Message


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('owner',)


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        exclude = ('owner',)


class ManagerMailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ('status',)


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('owner',)

    def clean_title(self):
        cleaned_data = self.cleaned_data['title']
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'обман']
        for word in forbidden_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError('Недопустимое слово в заголовке сообщения!')

        return cleaned_data

    def clean_message(self):
        cleaned_data = self.cleaned_data['message']
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'обман']
        for word in forbidden_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError('Недопустимое слово в сообщении!')

        return cleaned_data

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.services import get_articles_from_cache
from mailing.forms import ClientForm, MessageForm, MailingForm, ManagerMailingForm
from mailing.models import Message, Log


from django.views.generic import TemplateView

from mailing.models import Mailing, Client


class HomeView(TemplateView):
    """
    Контроллер главной страницы сайта
    """
    template_name = 'mailing/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        mailings = Mailing.objects.all()
        clients = Client.objects.all()
        context_data['all_mailings'] = mailings.count()
        context_data['active_mailings'] = mailings.filter(status=Mailing.STARTED).count()
        context_data['active_clients'] = clients.values('email').distinct().count()

        context_data['random_blogs'] = get_articles_from_cache().order_by('?')[:3]
        return context_data


class ClientListView(LoginRequiredMixin, ListView):
    """
    Контроллер отвечающий за отображение списка клиентов
    """
    model = Client

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='manager'):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class ClientDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер отвечающий за отображение клиента
    """
    model = Client

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class ClientCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер отвечающий за создание клиента
    """
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:clients_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер отвечающий за редактирование клиента
    """
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse('mailing:view', args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер отвечающий за удаление клиента
    """
    model = Client
    success_url = reverse_lazy('mailing:clients_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class MessageListView(LoginRequiredMixin, ListView):
    """
    Контроллер отвечающий за отображение списка сообщений
    """
    model = Message

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='manager'):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MessageDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер отвечающий за отображение сообщения
    """
    model = Message

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class MessageCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер отвечающий за создание сообщения
    """
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:messages_list')

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер отвечающий за редактирование сообщение
    """
    model = Message
    form_class = MessageForm

    def get_success_url(self):
        return reverse('mailing:view_message', args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер отвечающий за удаление сообщения
    """
    model = Message
    success_url = reverse_lazy('mailing:messages_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class MailingListView(LoginRequiredMixin, ListView):
    """
    Контроллер отвечающий за отображение списка рассылок
    """
    model = Mailing

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='manager'):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MailingDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер отвечающий за отображение рассылки
    """
    model = Mailing

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='manager') and user != self.object.owner:
            raise PermissionDenied
        else:
            return self.object


class MailingCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер отвечающий за создание рассылки
    """
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailings_list')

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер отвечающий за редактирование рассылки
    """
    model = Mailing
    form_class = MailingForm

    def get_success_url(self):
        return reverse('mailing:view_mailing', args=[self.kwargs.get('pk')])

    def get_form_class(self):
        """
        Функция, определяющая поля для редактирования в зависимости от прав пользователя
        """
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return MailingForm
        elif user.has_perm('mailing.deactivate_mailing'):
            return ManagerMailingForm
        else:
            raise PermissionDenied


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер отвечающий за удаление расылки
    """
    model = Mailing
    success_url = reverse_lazy('mailing:mailings_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class LogListView(LoginRequiredMixin, ListView):
    """
    Контроллер отвечающий за отображение списка попыток рассылок
    """
    model = Log

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Сервис рассылок</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
{% include 'mailing/includes/inc_menu.html' %}
</header>

<main role="main">

    {% block content %}
    {% endblock %}

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>&copy; 2024 - {% now 'Y' %}</p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<script src="{% static 'js/holder.min.js'%}"></script>
</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Удаление клиента</h1>
    </div>
</section>
<div class="col-6">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить клиента {{ object.name }}?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'mailing:clients_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html'%}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Информация о клиенте</h1>
    </div>
</section>

<div class="col-6">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <p class="card-text">Имя клиента: {{ client.name }}</p>
                    <p class="card-text">Email: {{ client.email }}</p>
                    <p class="card-text">Комментарий: {{ client.comment }}</p>
                    <p class="card-text">Добавил клиента: {{ client.owner }}</p>
                    <a class="btn btn-primary" href="{% url 'mailing:clients_list' %}" role="button">Назад</a>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html'%}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Список клиентов</h1>
    </div>
</section>
<a class="btn btn-outline-primary mb-5" href="{% url 'mailing:create' %}">Добавить клиента</a>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for client in object_list %}
    <div class="col-3 p-1">
        <div class="card shadow-sm">
            <div class="card-body">
                <p class="card-text">Имя клиента: {{ client.name }}</p>
                <p class="card-text">Email: {{ client.email }}</p>
                <p class="card-text">Комментарий: {{ client.comment }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        {% if user == client.owner or user.is_superuser %}
                        <a class="btn btn-primary" href="{% url 'mailing:view' client.pk %}" role="button">Просмотр</a>
                        <a class="btn btn-primary" href="{% url 'mailing:delete' client.pk %}" role="button">Удалить</a>
                        <a class="btn btn-primary" href="{% url 'mailing:edit' client.pk %}"
                           role="button">Редактировать</a>
                        {% endif %}


                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

mailing/templates/mailing/index.html
{% extends 'mailing/base.html'%}
{% load my_tags %}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Сервис управления рассылками</h1>
        <p class="lead text-muted">С помощью нашего сервиса вы можете создать email-рассылку для своих клиентов.</p>
        <p>
            {% if user.is_authenticated %}
            <a href="{% url 'mailing:create' %}" class="btn btn-primary my-2">Добавить клиента</a>
            <a href="{% url 'mailing:create_message' %}" class="btn btn-primary my-2">Добавить сообщение</a>
            <a href="{% url 'mailing:create_mailing' %}" class="btn btn-primary my-2">Создать рассылку</a>
            {% else %}
            <a href="{% url 'users:login' %}" class="btn btn-primary my-2">Вход</a>
            <a href="{% url 'users:register' %}" class="btn btn-primary my-2">Регистрация</a>
            {% endif %}
        <div class="col-6">
            <div class="card" style="width: 36rem;">
                <div class="card-header"><h5>Статистика рассылок</h5></div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Всего рассылок - {{all_mailings}}</li>
                    <li class="list-group-item">Активных рассылок - {{active_mailings}}</li>
                    <li class="list-group-item">Уникальных клиентов для рассылок - {{active_clients}}</li>
                </ul>
            </div>
        </div>
    </div>
</section>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for object in random_blogs %}
            <div class="col-4">
                <div class="card shadow-sm">
                    <img src="{{ object.preview | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">
                        <h2>{{ object.title}}</h2>
                        <p class="card-text">Содержание: {{ object.body }}</p>
                        <p class="card-text"> Создана {{ object.created_at }}</p>
                        <p class="card-text">Просмотры- {{ object.views_count }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/log_list.html
{% extends 'mailing/base.html'%}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Попытки рассылок</h1>
    </div>
</section>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">Рассылка</th>
        <th scope="col">Время</th>
        <th scope="col">Статус</th>
        <th scope="col">Ответ сервера</th>
    </tr>
    </thead>
    <tbody>
    {% for log in object_list %}
    <tr>
        <td>{{ log.mailing }}</td>
        <td>{{ log.time }}</td>
        <td>{{ log.status }}</td>
        <td>{{ log.server_response }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html'%}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Список рассылок</h1>
    </div>
</section>
{% if user.is_authenticated %}
<a class="btn btn-outline-primary mb-5" href="{% url 'mailing:create_mailing' %}">Создать рассылку</a>
{% endif %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for mailing in object_list %}
    <div class="col-3 p-1">
        <div class="card shadow-sm">
            <div class="card-body">
                <p class="card-text">Название: {{ mailing.name }}</p>
                <p class="card-text">Статус: {{ mailing.status }}</p>
                <p class="card-text">Периодичность: {{ mailing.periodicity }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        {% if perms.mailing.view_all_mailings or user == mailing.owner or user.is_superuser %}
                        <a class="btn btn-primary" href="{% url 'mailing:view_mailing' mailing.pk %}" role="button">Просмотр</a>
                        {% endif %}
                        {% if perms.mailing.deactivate_mailing or user == mailing.owner or user.is_superuser %}
                        <a class="btn btn-primary" href="{% url 'mailing:edit_mailing' mailing.pk %}"
                           role="button">Редактировать</a>
                        {% endif %}
                        {% if user == mailing.owner or user.is_superuser %}
                        <a class="btn btn-primary" href="{% url 'mailing:delete_mailing' mailing.pk %}" role="button">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html'%}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Список сообщений</h1>
    </div>
</section>
<a class="btn btn-outline-primary mb-5" href="{% url 'mailing:create_message' %}">Добавить сообщение</a>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for message in object_list %}
    <div class="col-3 p-1">
        <div class="card shadow-sm">
            <div class="card-body">
                <p class="card-text">Заголовок: {{ message.title }}</p>
                <p class="card-text">Сообщение: {{ message.message }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        {% if user == user.is_staff %}
                        <a class="btn btn-primary" href="{% url 'mailing:view_message' message.pk %}" role="button">Просмотр</a>
                        {% endif %}
                        {% if user == message.owner or user.is_superuser %}
                        <a class="btn btn-primary" href="{% url 'mailing:view_message' message.pk %}" role="button">Просмотр</a>
                        <a class="btn btn-primary" href="{% url 'mailing:edit_message' message.pk%}" role="button">Редактировать</a>
                        <a class="btn btn-primary" href="{% url 'mailing:delete_message' message.pk%}" role="button">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}