blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (BlogArticleCreateView, BlogArticleListView, BlogArticleDetailView, BlogArticleUpdateView,
                        BlogArticleDeleteView)

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogArticleCreateView.as_view(), name='create'),
    path('', BlogArticleListView.as_view(), name='list'),
    path('delete/<int:pk>/', BlogArticleDeleteView.as_view(), name='delete'),
    path('edit/<int:pk>/', BlogArticleUpdateView.as_view(), name='edit'),
    path('view/<int:pk>/', cache_page(60)(BlogArticleDetailView.as_view()), name='view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class BlogArticle(models.Model):
    """
    Модель для хранения информации о статье блога
    """
    title = models.CharField(max_length=100, verbose_name="Заголовок", help_text="Введите заголовок статьи")
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)
    body = models.TextField(verbose_name="Текст статьи", help_text="Введите текст статьи")
    preview = models.ImageField(upload_to="products/photo", verbose_name="Изображение",
                                help_text="Добавьте изображение", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

blog/forms.py
from django import forms
from .models import BlogArticle


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs['class'] = 'form-control'


class BlogArticleForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = BlogArticle
        fields = '__all__'

blog/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.forms import BlogArticleForm
from blog.models import BlogArticle
from blog.services import get_articles_from_cache


class BlogArticleCreateView(PermissionRequiredMixin, CreateView):
    """
    Контроллер, который отвечает за создание статьи блога
    """
    model = BlogArticle
    form_class = BlogArticleForm
    success_url = reverse_lazy('blog:list')
    permission_required = 'blog.add_blogarticle'

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()
        return super().form_valid(form)


class BlogArticleListView(ListView):
    """
    Контроллер, который отвечает за просмотр списка статей блога
    """
    model = BlogArticle

    def get_queryset(self, *args, **kwargs):
        queryset = get_articles_from_cache().filter(is_published=True)
        return queryset


class BlogArticleDetailView(DetailView):
    """
    Контроллер, который отвечает за просмотр статьи блога
    """
    model = BlogArticle

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogArticleUpdateView(PermissionRequiredMixin, UpdateView):
    """
    Контроллер, который отвечает за редактирование статьи блога
    """
    model = BlogArticle
    form_class = BlogArticleForm
    permission_required = 'blog.change_blogarticle'

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogArticleDeleteView(PermissionRequiredMixin, DeleteView):
    """
    Контроллер, который отвечает за удаление статьи блога
    """
    model = BlogArticle
    success_url = reverse_lazy('blog:list')
    permission_required = 'blog.delete_blogarticle'

blog/templates/blog/blogarticle_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row mt-5">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить запись"{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blogarticle_detail.html
{% extends 'mailing/base.html'%}
{% load my_tags %}
{% block content %}
<div class="col-12 mb-7">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col-4">
            <div class="card shadow-sm">
                <img src="{{ object.preview | media_filter }}">
                <div class="card-body">
                    <p class="card-text"><h2>{{ object.title}}</h2>
                    <p class="card-text">{{ object.slug }}</p>
                    <p class="card-text">Содержание: {{ object.body }}</p>
                    <p class="card-text"> Создана {{ object.created_at }}</p>
                    <p class="card-text">Просмотры- {{ object.views_count }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blogarticle_form.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row mt-5">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    {% if object %}
                    <h5 class="card-title">Редактирование статьи</h5>
                    {% else %}
                    <h5 class="card-title">Добавление статьи</h5>
                    {% endif %}
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blogarticle_list.html
{% extends 'mailing/base.html'%}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Блог</h1>
        <p class="lead text-muted">Новости и интересные факты</p>
    </div>
</section>
<div class="col-12 mb-5, mt-5">
    {% if perms.blog.add_blogarticle %}
    <a class="btn btn-outline-primary mt-5" href="{% url 'blog:create' %}">Создать запись</a>
    {% endif %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3, mt-5">
        {% for object in object_list %}
        <div class="col-3 p-1">
            <div class="card shadow-sm">
                <div class="card-body">
                    <p class="card-text">{{ object.title}}</p>
                    <p class="card-text">Содержание: {{ object.body|slice:100}}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'blog:view' object.pk %}" role="button">Просмотр</a>
                            {% if perms.blog.change_blogarticle %}
                            <a class="btn btn-primary" href="{% url 'blog:edit' object.pk %}" role="button">
                                Редактировать</a>
                            {% endif %}
                            {% if perms.blog.delete_blogarticle %}
                            <a class="btn btn-primary" href="{% url 'blog:delete' object.pk %}" role="button">
                                Удалить</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}