blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (BlogArticleCreateView, BlogArticleListView, BlogArticleDetailView, BlogArticleUpdateView,
                        BlogArticleDeleteView)

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogArticleCreateView.as_view(), name='create'),
    path('', BlogArticleListView.as_view(), name='list'),
    path('delete/<int:pk>/', BlogArticleDeleteView.as_view(), name='delete'),
    path('edit/<int:pk>/', BlogArticleUpdateView.as_view(), name='edit'),
    path('view/<int:pk>/', cache_page(60)(BlogArticleDetailView.as_view()), name='view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, reset_password, ProfileView, UserListView, toggle_activity

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('reset_password/', reset_password, name='reset_password'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('toggle_activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Еmail')
    phone = models.CharField(max_length=35, verbose_name='Телефон', blank=True, null=True)
    avatar = models.ImageField(upload_to='users/avatars/', verbose_name='Аватар', blank=True, null=True)
    token = models.CharField(max_length=100, verbose_name='Токен', blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            ('deactivate_user', 'Can deactivate user'),
            ('view_all_users', 'Can view all users'),
        ]

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from mailing.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
import string

from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView
import secrets
from config.settings import EMAIL_HOST_USER

from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(subject="Подтверждение почты",
                  message=f"Перейдите по ссылке для подтверждения почты {url}",
                  from_email=EMAIL_HOST_USER,
                  recipient_list=[user.email]
                  )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


def reset_password(request):
    context = {
        'success_message': 'Пароль успешно сброшен. Новый пароль был отправлен на ваш адрес электронной почты.',
    }
    if request.method == 'POST':
        email = request.POST.get('email')
        user = get_object_or_404(User, email=email)
        characters = string.ascii_letters + string.digits
        characters_list = list(characters)
        random.shuffle(characters_list)
        password = ''.join(characters_list[:10])

        user.set_password(password)
        user.save()

        send_mail(
            subject='Восстановление пароля',
            message=f'Здравствуйте, вы запрашивали обновление пароля. Ваш новый пароль: {password}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )

        return render(request, 'users/reset_password.html', context)

    return render(request, 'users/reset_password.html')


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserListView(PermissionRequiredMixin, ListView):
    model = User
    permission_required = 'users.view_all_users'


@permission_required('users.deactivate_user')
def toggle_activity(request, pk):
    user = User.objects.get(pk=pk)
    if user.is_active:
        user.is_active = False
    else:
        user.is_active = True
    user.save()
    return redirect(reverse('users:users_list'))

users/templates/users/login.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row mt-5" method="post" enctype="multipart/form-data">
        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Вход</h5>
                </div>
                <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>
                    <a href="{% url 'users:reset_password' %}" type="submit" class="btn btn-warning">
                        Восстановить пароль
                    </a>

                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/reset_password.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Восстановление пароля
                </h3>
            </div>
            <div class="card-body">
                {% if success_message %}
                <p>{{ success_message }}</p>
                <a href="{% url 'users:login' %}" class="btn btn-success">Войти в личный кабинет</a>
                {% else %}
                <form class="row" method="post">
                    {% csrf_token %}
                    <input type="email" name="email">
                    <button type="submit" class="btn btn-success">
                        Восстановить пароль
                    </button>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row mt-5" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                 <div class="card-header">
                    {% if object %}
                        <h5 class="card-title">Редактирование профиля</h5>
                    {% else %}
                        <h5 class="card-title">Регистрация</h5>
                    {% endif %}
                </div>
                <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}

                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Зарегистрироваться
                        {% endif %}
                    </button>

                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing/base.html'%}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Список пользователей</h1>
    </div>
</section>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">Email</th>
        <th scope="col">Телефон</th>
        <th scope="col">Статус</th>
        <th scope="col">Персонал</th>
        <th scope="col">Изменение сатуса</th>
    </tr>
    </thead>
    <tbody>
    {% for user in object_list %}
    <tr>
        <td>{{ user.email }}</td>
        <td>{{ user.phone }}</td>
        <td>{{ user.is_active }}</td>
        <td>{{ user.is_staff }}</td>
        <td>{% if perms.users.deactivate_user %}
            {% if user.is_active %}
            <a href="{% url 'users:toggle_activity' user.pk %}"
               class="btn btn-sm btn-outline-danger">Деактивировать</a>
            {% else %}
            <a href="{% url 'users:toggle_activity' user.pk %}"
               class="btn btn-sm btn-outline-success">Активировать</a>
            {% endif %}
            {% endif %}
        </td>

    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}